# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-08 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_review', '0004_auto_20180308_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_image',
        ),
    ]
